#!/usr/bin/env python3
"""Read-only FCHD coverage audit for the 252 additional FA Cup journey clubs.

Consumes journey-club-verification-queue.json generated by the registry audit in
this same workflow. It reports candidate evidence only and never changes live
Clubfinder, GROUNDS, competition, mileage, venue or journey data.
"""
from pathlib import Path
from collections import defaultdict
import html as htmlmod
import json
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
QUEUE = ROOT / 'updater' / 'journey-club-verification-queue.json'
OUT_JSON = ROOT / 'updater' / 'journey-ground-coverage-audit.json'
OUT_MD = ROOT / 'journey-ground-coverage-audit.md'
SOURCE_URL = 'https://fchd.info/maps/GAZ.htm'


def base(name):
    s = htmlmod.unescape(str(name or '')).lower().replace('&', ' and ')
    s = re.sub(r'\b(association football club|football club)\b', ' ', s)
    s = re.sub(r'[^a-z0-9]+', ' ', s).strip()
    return re.sub(r'\s+', ' ', s)


def identity_key(name):
    """Conservative identity: leading AFC remains significant."""
    s = base(name)
    s = re.sub(r'\b(fc|cfc)\b', ' ', s)
    s = re.sub(r'\bafc$', ' ', s)
    return re.sub(r'\s+', ' ', s).strip()


def relaxed_key(name):
    """Discovery-only key. Never sufficient by itself when ambiguous."""
    s = base(name)
    s = re.sub(r'\b(fc|afc|cfc)\b', ' ', s)
    return re.sub(r'\s+', ' ', s).strip()


def clean_markup(s):
    s = re.sub(r'<br\s*/?>', '\n', s, flags=re.I)
    s = re.sub(r'<[^>]+>', '\n', s)
    return [htmlmod.unescape(x).strip(' \t\r\n|') for x in s.splitlines()
            if htmlmod.unescape(x).strip(' \t\r\n|')]


def parse_fchd(raw):
    pat = re.compile(r'<h3\b[^>]*>(.*?)</h3>(.*?)(?=<h3\b|<h1\b|$)', re.I | re.S)
    pc_re = re.compile(r'\b(?:GIR 0AA|(?:[A-Z]{1,2}\d[A-Z\d]?|\d[A-Z]{2})\s*\d[A-Z]{2})\b', re.I)
    rows = []
    for head, body in pat.findall(raw):
        club = ' '.join(clean_markup(head))
        lines = clean_markup(body)
        postcode = None
        for line in lines:
            m = pc_re.search(line)
            if m:
                postcode = re.sub(r'\s+', ' ', m.group(0).upper()).strip()
                break
        if not club or not postcode:
            continue
        useful = [x for x in lines
                  if not pc_re.fullmatch(x)
                  and not re.search(r'-?\d{1,2}\.\d+\s*,\s*-?\d{1,3}\.\d+', x)
                  and not x.lower().startswith(('http://', 'https://'))]
        ground = useful[0] if useful else 'Ground TBC'
        if len(useful) > 1 and re.search(r'\b(FC|AFC|CFC|Town|United|Athletic|Rovers|City)$', ground, re.I):
            ground = useful[1]
        rows.append({'club': club, 'ground': ground, 'postcode': postcode, 'source': SOURCE_URL})
    return rows


if not QUEUE.exists():
    raise SystemExit('ABORT: journey verification queue missing; registry audit must run first')
queue = json.loads(QUEUE.read_text(encoding='utf-8')).get('clubs', [])
if len(queue) != 252:
    raise SystemExit(f'ABORT: expected 252 additional journey clubs, found {len(queue)}')

req = urllib.request.Request(
    SOURCE_URL,
    headers={'User-Agent': 'Mozilla/5.0 TinFoilFACupJourneyGroundAudit/1.0', 'Accept': 'text/html,*/*'}
)
with urllib.request.urlopen(req, timeout=40) as r:
    raw = r.read().decode('utf-8', 'replace')
gaz = parse_fchd(raw)
if len(gaz) < 750:
    raise SystemExit(f'ABORT: FCHD parser returned suspiciously few records: {len(gaz)}')

by_identity = defaultdict(list)
by_relaxed = defaultdict(list)
for row in gaz:
    by_identity[identity_key(row['club'])].append(row)
    by_relaxed[relaxed_key(row['club'])].append(row)

# Queue itself is the authoritative scope. A relaxed match may be classified as a
# unique candidate only when one FCHD row AND one queue identity share that key.
queue_by_relaxed = defaultdict(list)
for item in queue:
    queue_by_relaxed[relaxed_key(item['club'])].append(item['club'])

results = []
for item in queue:
    club = item['club']
    existing = item.get('existing_ground_record')
    if existing:
        results.append({
            **item,
            'coverage_status': 'existing-ground-record',
            'fchd_candidates': [],
            'note': 'Already has a guarded existing GROUNDS record; FCHD not needed for coverage.'
        })
        continue

    exact = by_identity.get(identity_key(club), [])
    if len(exact) == 1:
        status = 'fchd-unique-identity-candidate'
        candidates = exact
    elif len(exact) > 1:
        status = 'fchd-ambiguous-identity'
        candidates = exact
    else:
        relaxed = by_relaxed.get(relaxed_key(club), [])
        scoped_peers = queue_by_relaxed.get(relaxed_key(club), [])
        if len(relaxed) == 1 and len(scoped_peers) == 1:
            status = 'fchd-unique-relaxed-candidate'
            candidates = relaxed
        elif relaxed:
            status = 'fchd-ambiguous-relaxed'
            candidates = relaxed
        else:
            status = 'unresolved'
            candidates = []

    results.append({**item, 'coverage_status': status, 'fchd_candidates': candidates})

counts = defaultdict(int)
for x in results:
    counts[x['coverage_status']] += 1

existing = counts['existing-ground-record']
unique_identity = counts['fchd-unique-identity-candidate']
unique_relaxed = counts['fchd-unique-relaxed-candidate']
amb_identity = counts['fchd-ambiguous-identity']
amb_relaxed = counts['fchd-ambiguous-relaxed']
unresolved = counts['unresolved']
unique_total = unique_identity + unique_relaxed
review_total = amb_identity + amb_relaxed + unresolved

if sum(counts.values()) != 252:
    raise SystemExit(f'ABORT: coverage partition does not total 252: {dict(counts)}')

report = {
    'scope_additional_journey_clubs': 252,
    'fchd_records_parsed': len(gaz),
    'existing_guarded_ground_records': existing,
    'fchd_unique_identity_candidates': unique_identity,
    'fchd_unique_relaxed_candidates': unique_relaxed,
    'fchd_unique_candidates_total': unique_total,
    'fchd_ambiguous_identity': amb_identity,
    'fchd_ambiguous_relaxed': amb_relaxed,
    'unresolved': unresolved,
    'needs_non_fchd_or_manual_review': review_total,
    'results': results,
    'source': SOURCE_URL,
    'read_only': True,
    'candidate_evidence_only': True,
}
OUT_JSON.write_text(json.dumps(report, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')

md = [
    '# Journey Ground Coverage — Read-only FCHD audit', '',
    f'- Additional journey clubs audited: **252**',
    f'- FCHD records parsed: **{len(gaz)}**',
    f'- Existing guarded GROUNDS records: **{existing}**',
    f'- Unique FCHD identity candidates: **{unique_identity}**',
    f'- Unique FCHD relaxed-name candidates: **{unique_relaxed}**',
    f'- Total unique FCHD candidates: **{unique_total}**',
    f'- Ambiguous FCHD identity matches: **{amb_identity}**',
    f'- Ambiguous FCHD relaxed matches: **{amb_relaxed}**',
    f'- Unresolved in FCHD: **{unresolved}**',
    f'- Need non-FCHD / manual evidence review: **{review_total}**', '',
    '## Ambiguous / unresolved review queue'
]
review = [x for x in results if x['coverage_status'] in ('fchd-ambiguous-identity', 'fchd-ambiguous-relaxed', 'unresolved')]
if review:
    for x in review:
        cands = ', '.join(f"{c['club']} — {c['ground']} — {c['postcode']}" for c in x['fchd_candidates'])
        md.append(f"- {x['club']} — {x['entry_round']} — **{x['coverage_status']}**" + (f" — candidates: {cands}" if cands else ''))
else:
    md.append('- None')
md += ['', '## Safety',
       '- READ ONLY: no Clubfinder, competition, GROUNDS, venue, mileage or journey data changed.',
       '- FCHD matches are candidate evidence only; they are not automatically promoted to verified registry records.',
       '- Leading AFC remains identity-significant; relaxed matching is accepted only when unique in both FCHD and the 252-club queue.',
       '- Ambiguous and unresolved clubs remain explicitly queued for stronger official/league/club evidence.']
OUT_MD.write_text('\n'.join(md) + '\n', encoding='utf-8')

print('JOURNEY GROUND COVERAGE AUDIT: SUCCESS')
print('Additional journey clubs:', 252)
print('FCHD records parsed:', len(gaz))
print('Existing guarded GROUNDS:', existing)
print('Unique FCHD identity candidates:', unique_identity)
print('Unique FCHD relaxed candidates:', unique_relaxed)
print('Unique FCHD candidates total:', unique_total)
print('Ambiguous identity:', amb_identity)
print('Ambiguous relaxed:', amb_relaxed)
print('Unresolved:', unresolved)
print('Needs non-FCHD/manual review:', review_total)
print('READ ONLY: candidate evidence only')
