#!/usr/bin/env node
const fs=require('fs');const vm=require('vm');const path=require('path');
const ROOT=path.resolve(__dirname,'..');const html=fs.readFileSync(path.join(ROOT,'clubfinder.html'),'utf8');const competition=JSON.parse(fs.readFileSync(path.join(ROOT,'competition.json'),'utf8'));const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).join('\n');
if(!html.includes('const top=rows.slice(0,3);'))throw new Error('Nearest-three source guard missing');
function stub(){return {value:'',textContent:'',innerHTML:'',style:{},disabled:false,hidden:false,dataset:{},addEventListener(){},focus(){},setAttribute(){},removeAttribute(){},appendChild(){},remove(){},insertAdjacentElement(){},classList:{add(){},remove(){}}}}
const els=new Proxy({}, {get:(o,k)=>o[k]||(o[k]=stub())});const document={readyState:'complete',getElementById(id){return els[id]},querySelector(){return stub()},querySelectorAll(){return []},createElement(){return stub()},addEventListener(){},body:stub()};
const sandbox={console,process,document,MutationObserver:undefined,localStorage:{getItem(){return null},setItem(){},removeItem(){}},navigator:{},location:{href:'https://example.test/clubfinder.html'},URL,URLSearchParams,TextEncoder,TextDecoder,setTimeout,clearTimeout,fetch:async(url)=>{if(String(url).includes('competition.json'))return {ok:true,json:async()=>competition,text:async()=>JSON.stringify(competition)};throw new Error('Unexpected network request: '+url)}};sandbox.window=sandbox;sandbox.globalThis=sandbox;vm.createContext(sandbox);
const test=`(async()=>{
 if(ELIGIBLE.length!==651)throw Error('Expected 651 Law 2 origins, got '+ELIGIBLE.length);
 const expected={'Extra Preliminary Round':438,'Preliminary Round':53,'First Round Qualifying':88,'Second Round Qualifying':48,'Fourth Round Qualifying':24};const counts={};for(const c of ELIGIBLE)counts[c.entry_round]=(counts[c.entry_round]||0)+1;
 for(const [round,n] of Object.entries(expected))if(counts[round]!==n)throw Error('Entry-round count drift for '+round+': '+counts[round]+' expected '+n);if(Object.keys(counts).length!==Object.keys(expected).length)throw Error('Unexpected entry-round cohort: '+JSON.stringify(counts));
 if(ELIGIBLE.some(c=>/Round Proper/.test(c.entry_round||'')))throw Error('Proper-round entrant present');if(ELIGIBLE.some(c=>c.entry_round==='Third Round Qualifying'))throw Error('Unexpected Third Qualifying entrant cohort');if(new Set(ELIGIBLE.map(c=>norm(c.name))).size!==651)throw Error('Duplicate origins');
 const kendal=ELIGIBLE.find(c=>norm(c.name)===norm('Kendal Town FC'));if(!kendal||kendal.entry_round!=='Extra Preliminary Round')throw Error('Kendal Town official entry-round correction missing');
 const leather=ELIGIBLE.find(c=>norm(c.name)===norm('Leatherhead FC'));if(!leather||leather.entry_round!=='First Round Qualifying')throw Error('Leatherhead entry missing/wrong');const lg=findGround(leather);if(!lg||lg.postcode!=='KT22 9AS'||!/Fetcham Grove/i.test(lg.ground||''))throw Error('Leatherhead location wrong: '+JSON.stringify(lg));if(!Number.isFinite(Number(lg.lat))||!Number.isFinite(Number(lg.lon)))throw Error('Leatherhead coordinates missing');if((lg.verification||'').toLowerCase()==='verified')throw Error('Leatherhead supporting evidence silently promoted');
 const warrington=ELIGIBLE.find(c=>norm(c.name)===norm('Warrington Rylands'));const wg=findGround(warrington);if(!wg||wg.postcode!=='WA2 7RZ')throw Error('Warrington Rylands official postcode override missing: '+JSON.stringify(wg));
 const rows=[];for(const c of ELIGIBLE){const g=findGround(c);if(!g)throw Error('No origin location for '+c.name);if(!Number.isFinite(Number(g.lat))||!Number.isFinite(Number(g.lon)))throw Error('No origin coordinates for '+c.name);rows.push({...c,...g,distance:hav({lat:Number(lg.lat),lon:Number(lg.lon)},{lat:Number(g.lat),lon:Number(g.lon)})})}rows.sort((a,b)=>a.distance-b.distance);const top=rows.slice(0,3);if(top.length!==3)throw Error('Nearest journey count changed');if(norm(top[0].name)!==norm('Leatherhead FC'))throw Error('KT22 9AS canary ranks '+top[0].name+' first');
 const journey=buildJourney(leather),history=previousRoundsHtml(journey),copy='Leatherhead FC enters the competition at First Round Qualifying.';if(!history.includes(copy))throw Error('Entry explanation missing: '+history);if((journey.breadcrumbs||[]).some(x=>['Extra Preliminary Round','Preliminary Round'].includes((x.result||{}).round||x.round)))throw Error('Leatherhead fabricated pre-entry history');
 console.log('LAW 2 ORIGIN REGRESSION: PASS');console.log('Selectable origins: 651');console.log('Entry cohorts:',JSON.stringify(counts));console.log('Kendal Town FC -> Extra Preliminary Round: PASS');console.log('KT22 9AS -> Leatherhead FC:',lg.ground,'•',lg.postcode);console.log('Leatherhead entry explanation: PASS');console.log('Warrington Rylands current postcode: WA2 7RZ');console.log('Nearest journeys returned: 3');console.log('Proper-round-only origins excluded: PASS');
})().catch(e=>{console.error(e.stack||e);process.exitCode=1});`;
try{vm.runInContext(scripts+'\n'+test,sandbox,{filename:'clubfinder.html'});}catch(e){console.error(e.stack||e);process.exit(1)}
