const fs=require('fs');
const html=fs.readFileSync('beta/clubfinder-beta.html','utf8');
const campaign=[...html.matchAll(/\['(02|05|08|11|13|16|17|18|19|20|22|25|26|27)'\s*,/g)].map(m=>m[1]);
const honour=[...html.matchAll(/\['(01|03|04|06|07|09|10|14|23)'\s*,/g)].map(m=>m[1]);
if(new Set(campaign).size!==14)throw new Error('Stats truth must define exactly 14 Campaign Challenges');
if(new Set(honour).size!==9)throw new Error('Stats truth must define exactly 9 Honour Challenges');
if(!html.includes("deck&&deck.campaignKey===tinFoilChallengeCampaignKey(truth)"))throw new Error('Honour snapshot must be isolated to the matching Campaign');
if(!html.includes("return selected?[origin,selected].join('|'):[origin,callSign].join('|')"))throw new Error('Stats truth must use the Deck campaign-key contract');
if(!html.includes("verification:'campaign'")||!html.includes("verification:'honour'"))throw new Error('Stats snapshot must retain verification class');
if(html.includes("challengeHonours:tinFoilChallengeHonoursSnapshot"))throw new Error('Challenge honours must not change the locked Stage C bridge schema');
if(!html.includes("function tinFoilChallengeHonoursSnapshot(truth,progress)"))throw new Error('Stats honours collector missing');
if(!html.includes("const finalChallengeHonours=tinFoilChallengeHonoursSnapshot(challengeTruth"))throw new Error('Stats generation must collect permanent Challenge honours');
if(!html.includes("tinFoilChallengeCampaignKey(bridge)===tinFoilChallengeCampaignKey(challengeTruth)"))throw new Error('Giant Killer bridge evidence must match the certified Campaign');
for(const id of ['12','15','21','24'])if(new RegExp("\\['"+id+"'\\s*,").test(html))throw new Error('Coming Soon challenge '+id+' must not enter permanent Stats truth');
console.log('BETA CHALLENGE HONOURS STATS TRUTH: PASS');
